version: '3'

services:
  node1:
    image: leoimages:image1
    build:
      context: ./
      dockerfile: DockerFileNodes
    ports:
      - "3000:3001"
      - "7051:7051"
    volumes:
      - ./node1:/home/app

  node2:
    image: leoimages:image1
    build:
      context: ./
      dockerfile: DockerFileNodes
    ports:
      - "3000:3002"
    volumes:
      - ./node2:/home/app


  node3:
    image: leoimages:image1
    build:
      context: ./
      dockerfile: DockerFileNodes
    ports:
      - "3000:3003"
    volumes:
      - ./node3:/home/app

  node4:
    image: leoimages:image1
    build:
      context: ./
      dockerfile: DockerFileNodes
    ports:
      - "3000:3004"
    volumes:
      - ./node4:/home/app

  node5:
    image: leoimages:image1
    build:
      context: ./
      dockerfile: DockerFileNodes
    ports:
      - "3000:3005"
    volumes:
      - ./node5:/home/app
